

const FoodLogSeed = [{
    "name": "eggs",
    "sugar": 31,
    "calories": 161,
    "totalFat": 24,
    "sodium": 136,
    "protein": 12,
    "carbs": 39,
    "userId": 6,
    "servingUnit": "eggs",
    "quantity": 5,
    "date": "2018-01-10 11:49:31.029-06"
  },
  {
    "name": "pudding",
    "sugar": 24,
    "calories": 61,
    "totalFat": 23,
    "sodium": 135,
    "protein": 4,
    "carbs": 2,
    "userId": 4,
    "servingUnit": "medium",
    "quantity": 3,
    "date": "4/24/2018"
  },
  {
    "name": "lasagna",
    "sugar": 27,
    "calories": 17,
    "totalFat": 5,
    "sodium": 57,
    "protein": 10,
    "carbs": 28,
    "userId": 8,
    "servingUnit": "",
    "quantity": 4,
    "date": "5/4/2018"
  },
  {
    "name": "cookie",
    "sugar": 3,
    "calories": 266,
    "totalFat": 20,
    "sodium": 97,
    "protein": 5,
    "carbs": 25,
    "userId": 4,
    "servingUnit": "oz",
    "quantity": 5,
    "date": "5/16/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 9,
    "calories": 217,
    "totalFat": 9,
    "sodium": 73,
    "protein": 10,
    "carbs": 13,
    "userId": 6,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "5/16/2018"
  },
  {
    "name": "lasagna",
    "sugar": 2,
    "calories": 44,
    "totalFat": 24,
    "sodium": 89,
    "protein": 15,
    "carbs": 34,
    "userId": 3,
    "servingUnit": "gallon",
    "quantity": 5,
    "date": "5/7/2018"
  },
  {
    "name": "sausage",
    "sugar": 1,
    "calories": 244,
    "totalFat": 22,
    "sodium": 56,
    "protein": 11,
    "carbs": 37,
    "userId": 6,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "4/29/2018"
  },
  {
    "name": "yogurt",
    "sugar": 16,
    "calories": 257,
    "totalFat": 11,
    "sodium": 130,
    "protein": 13,
    "carbs": 5,
    "userId": 7,
    "servingUnit": "cup",
    "quantity": 4,
    "date": "5/13/2018"
  },
  {
    "name": "cola",
    "sugar": 2,
    "calories": 212,
    "totalFat": 25,
    "sodium": 121,
    "protein": 1,
    "carbs": 37,
    "userId": 4,
    "servingUnit": "bucket",
    "quantity": 5,
    "date": "5/7/2018"
  },
  {
    "name": "pork-chops",
    "sugar": 8,
    "calories": 174,
    "totalFat": 13,
    "sodium": 129,
    "protein": 1,
    "carbs": 45,
    "userId": 5,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "5/4/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 27,
    "calories": 153,
    "totalFat": 3,
    "sodium": 127,
    "protein": 8,
    "carbs": 15,
    "userId": 9,
    "servingUnit": "small",
    "quantity": 2,
    "date": "4/24/2018"
  },
  {
    "name": "popcorn",
    "sugar": 35,
    "calories": 181,
    "totalFat": 7,
    "sodium": 139,
    "protein": 8,
    "carbs": 26,
    "userId": 5,
    "servingUnit": "",
    "quantity": 4,
    "date": "4/22/2018"
  },
  {
    "name": "meatballs",
    "sugar": 20,
    "calories": 52,
    "totalFat": 8,
    "sodium": 120,
    "protein": 11,
    "carbs": 47,
    "userId": 4,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "5/10/2018"
  },
  {
    "name": "beer",
    "sugar": 3,
    "calories": 245,
    "totalFat": 8,
    "sodium": 141,
    "protein": 4,
    "carbs": 37,
    "userId": 4,
    "servingUnit": "small",
    "quantity": 1,
    "date": "4/26/2018"
  },
  {
    "name": "bacon",
    "sugar": 27,
    "calories": 149,
    "totalFat": 25,
    "sodium": 69,
    "protein": 7,
    "carbs": 33,
    "userId": 8,
    "servingUnit": "handful",
    "quantity": 3,
    "date": "5/1/2018"
  },
  {
    "name": "yogurt",
    "sugar": 30,
    "calories": 260,
    "totalFat": 18,
    "sodium": 109,
    "protein": 4,
    "carbs": 36,
    "userId": 4,
    "servingUnit": "much",
    "quantity": 2,
    "date": "4/29/2018"
  },
  {
    "name": "bacon",
    "sugar": 13,
    "calories": 78,
    "totalFat": 10,
    "sodium": 87,
    "protein": 5,
    "carbs": 3,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "4/30/2018"
  },
  {
    "name": "hot chocolate",
    "sugar": 2,
    "calories": 213,
    "totalFat": 8,
    "sodium": 132,
    "protein": 5,
    "carbs": 29,
    "userId": 5,
    "servingUnit": "L",
    "quantity": 1,
    "date": "5/15/2018"
  },
  {
    "name": "orange juice",
    "sugar": 12,
    "calories": 234,
    "totalFat": 2,
    "sodium": 86,
    "protein": 14,
    "carbs": 13,
    "userId": 9,
    "servingUnit": "L",
    "quantity": 4,
    "date": "5/5/2018"
  },
  {
    "name": "lasagna",
    "sugar": 29,
    "calories": 258,
    "totalFat": 19,
    "sodium": 57,
    "protein": 7,
    "carbs": 49,
    "userId": 9,
    "servingUnit": "lbs",
    "quantity": 5,
    "date": "5/2/2018"
  },
  {
    "name": "sausage",
    "sugar": 8,
    "calories": 86,
    "totalFat": 22,
    "sodium": 82,
    "protein": 9,
    "carbs": 44,
    "userId": 6,
    "servingUnit": "medium",
    "quantity": 5,
    "date": "5/8/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 30,
    "calories": 279,
    "totalFat": 25,
    "sodium": 2,
    "protein": 6,
    "carbs": 24,
    "userId": 3,
    "servingUnit": "",
    "quantity": 3,
    "date": "4/28/2018"
  },
  {
    "name": "popcorn",
    "sugar": 2,
    "calories": 134,
    "totalFat": 8,
    "sodium": 46,
    "protein": 8,
    "carbs": 43,
    "userId": 6,
    "servingUnit": "oz",
    "quantity": 5,
    "date": "5/16/2018"
  },
  {
    "name": "meatballs",
    "sugar": 29,
    "calories": 102,
    "totalFat": 9,
    "sodium": 25,
    "protein": 10,
    "carbs": 19,
    "userId": 8,
    "servingUnit": "handful",
    "quantity": 2,
    "date": "5/8/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 16,
    "calories": 286,
    "totalFat": 2,
    "sodium": 121,
    "protein": 10,
    "carbs": 47,
    "userId": 10,
    "servingUnit": "much",
    "quantity": 4,
    "date": "5/14/2018"
  },
  {
    "name": "beer",
    "sugar": 17,
    "calories": 229,
    "totalFat": 16,
    "sodium": 106,
    "protein": 10,
    "carbs": 3,
    "userId": 4,
    "servingUnit": "handful",
    "quantity": 5,
    "date": "5/9/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 25,
    "calories": 210,
    "totalFat": 4,
    "sodium": 82,
    "protein": 1,
    "carbs": 26,
    "userId": 4,
    "servingUnit": "bucket",
    "quantity": 1,
    "date": "5/12/2018"
  },
  {
    "name": "grapes",
    "sugar": 9,
    "calories": 115,
    "totalFat": 6,
    "sodium": 2,
    "protein": 3,
    "carbs": 50,
    "userId": 2,
    "servingUnit": "cup",
    "quantity": 5,
    "date": "5/17/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 34,
    "calories": 45,
    "totalFat": 5,
    "sodium": 46,
    "protein": 12,
    "carbs": 8,
    "userId": 3,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "4/27/2018"
  },
  {
    "name": "sausage",
    "sugar": 4,
    "calories": 245,
    "totalFat": 9,
    "sodium": 77,
    "protein": 8,
    "carbs": 39,
    "userId": 2,
    "servingUnit": "gallon",
    "quantity": 2,
    "date": "4/23/2018"
  },
  {
    "name": "cola",
    "sugar": 14,
    "calories": 16,
    "totalFat": 22,
    "sodium": 93,
    "protein": 6,
    "carbs": 34,
    "userId": 10,
    "servingUnit": "",
    "quantity": 3,
    "date": "5/4/2018"
  },
  {
    "name": "shrimp",
    "sugar": 11,
    "calories": 254,
    "totalFat": 25,
    "sodium": 23,
    "protein": 6,
    "carbs": 33,
    "userId": 3,
    "servingUnit": "",
    "quantity": 3,
    "date": "5/11/2018"
  },
  {
    "name": "meatballs",
    "sugar": 8,
    "calories": 78,
    "totalFat": 13,
    "sodium": 31,
    "protein": 14,
    "carbs": 48,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 4,
    "date": "4/20/2018"
  },
  {
    "name": "lasagna",
    "sugar": 15,
    "calories": 119,
    "totalFat": 7,
    "sodium": 37,
    "protein": 11,
    "carbs": 27,
    "userId": 6,
    "servingUnit": "medium",
    "quantity": 4,
    "date": "5/1/2018"
  },
  {
    "name": "cola",
    "sugar": 14,
    "calories": 226,
    "totalFat": 9,
    "sodium": 148,
    "protein": 2,
    "carbs": 37,
    "userId": 4,
    "servingUnit": "small",
    "quantity": 4,
    "date": "5/17/2018"
  },
  {
    "name": "bacon",
    "sugar": 11,
    "calories": 53,
    "totalFat": 22,
    "sodium": 80,
    "protein": 7,
    "carbs": 1,
    "userId": 1,
    "servingUnit": "L",
    "quantity": 4,
    "date": "5/2/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 31,
    "calories": 30,
    "totalFat": 1,
    "sodium": 25,
    "protein": 13,
    "carbs": 22,
    "userId": 8,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "5/13/2018"
  },
  {
    "name": "lasagna",
    "sugar": 12,
    "calories": 131,
    "totalFat": 1,
    "sodium": 24,
    "protein": 12,
    "carbs": 49,
    "userId": 6,
    "servingUnit": "",
    "quantity": 2,
    "date": "5/19/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 19,
    "calories": 199,
    "totalFat": 11,
    "sodium": 108,
    "protein": 5,
    "carbs": 42,
    "userId": 6,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "5/2/2018"
  },
  {
    "name": "turkey",
    "sugar": 13,
    "calories": 116,
    "totalFat": 24,
    "sodium": 17,
    "protein": 3,
    "carbs": 8,
    "userId": 9,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/17/2018"
  },
  {
    "name": "shrimp",
    "sugar": 26,
    "calories": 300,
    "totalFat": 1,
    "sodium": 83,
    "protein": 8,
    "carbs": 16,
    "userId": 10,
    "servingUnit": "handful",
    "quantity": 2,
    "date": "5/17/2018"
  },
  {
    "name": "sausage",
    "sugar": 28,
    "calories": 257,
    "totalFat": 23,
    "sodium": 83,
    "protein": 15,
    "carbs": 8,
    "userId": 7,
    "servingUnit": "small",
    "quantity": 1,
    "date": "5/6/2018"
  },
  {
    "name": "eggs",
    "sugar": 18,
    "calories": 191,
    "totalFat": 4,
    "sodium": 120,
    "protein": 10,
    "carbs": 16,
    "userId": 6,
    "servingUnit": "L",
    "quantity": 4,
    "date": "5/5/2018"
  },
  {
    "name": "eggs",
    "sugar": 13,
    "calories": 231,
    "totalFat": 6,
    "sodium": 83,
    "protein": 8,
    "carbs": 27,
    "userId": 9,
    "servingUnit": "L",
    "quantity": 4,
    "date": "5/16/2018"
  },
  {
    "name": "shrimp",
    "sugar": 28,
    "calories": 241,
    "totalFat": 22,
    "sodium": 72,
    "protein": 10,
    "carbs": 20,
    "userId": 4,
    "servingUnit": "cup",
    "quantity": 5,
    "date": "5/18/2018"
  },
  {
    "name": "apple",
    "sugar": 35,
    "calories": 105,
    "totalFat": 14,
    "sodium": 87,
    "protein": 7,
    "carbs": 20,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/1/2018"
  },
  {
    "name": "mac'n'cheese",
    "sugar": 35,
    "calories": 277,
    "totalFat": 10,
    "sodium": 86,
    "protein": 11,
    "carbs": 9,
    "userId": 7,
    "servingUnit": "much",
    "quantity": 3,
    "date": "5/15/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 6,
    "calories": 60,
    "totalFat": 10,
    "sodium": 68,
    "protein": 5,
    "carbs": 44,
    "userId": 5,
    "servingUnit": "medium",
    "quantity": 4,
    "date": "5/10/2018"
  },
  {
    "name": "milk",
    "sugar": 27,
    "calories": 7,
    "totalFat": 17,
    "sodium": 135,
    "protein": 7,
    "carbs": 43,
    "userId": 10,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "4/25/2018"
  },
  {
    "name": "mac'n'cheese",
    "sugar": 35,
    "calories": 149,
    "totalFat": 17,
    "sodium": 129,
    "protein": 1,
    "carbs": 21,
    "userId": 8,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "4/28/2018"
  },
  {
    "name": "eggs",
    "sugar": 7,
    "calories": 135,
    "totalFat": 25,
    "sodium": 83,
    "protein": 1,
    "carbs": 49,
    "userId": 8,
    "servingUnit": "",
    "quantity": 5,
    "date": "4/30/2018"
  },
  {
    "name": "shrimp",
    "sugar": 20,
    "calories": 118,
    "totalFat": 10,
    "sodium": 95,
    "protein": 7,
    "carbs": 4,
    "userId": 5,
    "servingUnit": "",
    "quantity": 2,
    "date": "5/2/2018"
  },
  {
    "name": "carrots",
    "sugar": 14,
    "calories": 150,
    "totalFat": 19,
    "sodium": 50,
    "protein": 15,
    "carbs": 47,
    "userId": 1,
    "servingUnit": "handful",
    "quantity": 5,
    "date": "4/29/2018"
  },
  {
    "name": "sausage",
    "sugar": 21,
    "calories": 178,
    "totalFat": 14,
    "sodium": 26,
    "protein": 3,
    "carbs": 16,
    "userId": 10,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "4/29/2018"
  },
  {
    "name": "grapes",
    "sugar": 2,
    "calories": 300,
    "totalFat": 3,
    "sodium": 61,
    "protein": 5,
    "carbs": 48,
    "userId": 6,
    "servingUnit": "gallon",
    "quantity": 5,
    "date": "4/30/2018"
  },
  {
    "name": "sausage",
    "sugar": 1,
    "calories": 273,
    "totalFat": 1,
    "sodium": 19,
    "protein": 13,
    "carbs": 2,
    "userId": 7,
    "servingUnit": "L",
    "quantity": 3,
    "date": "5/10/2018"
  },
  {
    "name": "pudding",
    "sugar": 17,
    "calories": 68,
    "totalFat": 17,
    "sodium": 75,
    "protein": 13,
    "carbs": 25,
    "userId": 1,
    "servingUnit": "",
    "quantity": 4,
    "date": "5/12/2018"
  },
  {
    "name": "lasagna",
    "sugar": 20,
    "calories": 188,
    "totalFat": 6,
    "sodium": 83,
    "protein": 1,
    "carbs": 16,
    "userId": 10,
    "servingUnit": "handful",
    "quantity": 4,
    "date": "5/4/2018"
  },
  {
    "name": "pudding",
    "sugar": 1,
    "calories": 89,
    "totalFat": 11,
    "sodium": 91,
    "protein": 10,
    "carbs": 35,
    "userId": 6,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/1/2018"
  },
  {
    "name": "wine",
    "sugar": 26,
    "calories": 52,
    "totalFat": 17,
    "sodium": 11,
    "protein": 1,
    "carbs": 18,
    "userId": 3,
    "servingUnit": "much",
    "quantity": 3,
    "date": "5/8/2018"
  },
  {
    "name": "orange juice",
    "sugar": 30,
    "calories": 250,
    "totalFat": 10,
    "sodium": 60,
    "protein": 5,
    "carbs": 16,
    "userId": 4,
    "servingUnit": "cup",
    "quantity": 2,
    "date": "5/9/2018"
  },
  {
    "name": "eggs",
    "sugar": 17,
    "calories": 289,
    "totalFat": 10,
    "sodium": 65,
    "protein": 1,
    "carbs": 47,
    "userId": 10,
    "servingUnit": "",
    "quantity": 2,
    "date": "4/24/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 21,
    "calories": 38,
    "totalFat": 17,
    "sodium": 54,
    "protein": 4,
    "carbs": 31,
    "userId": 3,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/15/2018"
  },
  {
    "name": "ribs",
    "sugar": 19,
    "calories": 147,
    "totalFat": 1,
    "sodium": 67,
    "protein": 14,
    "carbs": 21,
    "userId": 8,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "5/5/2018"
  },
  {
    "name": "beer",
    "sugar": 25,
    "calories": 263,
    "totalFat": 7,
    "sodium": 136,
    "protein": 10,
    "carbs": 25,
    "userId": 10,
    "servingUnit": "much",
    "quantity": 5,
    "date": "4/30/2018"
  },
  {
    "name": "pork-chops",
    "sugar": 15,
    "calories": 135,
    "totalFat": 3,
    "sodium": 37,
    "protein": 5,
    "carbs": 40,
    "userId": 10,
    "servingUnit": "much",
    "quantity": 1,
    "date": "5/7/2018"
  },
  {
    "name": "coffee",
    "sugar": 13,
    "calories": 228,
    "totalFat": 23,
    "sodium": 28,
    "protein": 11,
    "carbs": 45,
    "userId": 1,
    "servingUnit": "medium",
    "quantity": 4,
    "date": "4/22/2018"
  },
  {
    "name": "meatballs",
    "sugar": 21,
    "calories": 81,
    "totalFat": 18,
    "sodium": 102,
    "protein": 1,
    "carbs": 46,
    "userId": 5,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "4/28/2018"
  },
  {
    "name": "meatballs",
    "sugar": 21,
    "calories": 2,
    "totalFat": 14,
    "sodium": 27,
    "protein": 11,
    "carbs": 23,
    "userId": 3,
    "servingUnit": "cup",
    "quantity": 5,
    "date": "5/7/2018"
  },
  {
    "name": "shrimp",
    "sugar": 20,
    "calories": 6,
    "totalFat": 18,
    "sodium": 121,
    "protein": 2,
    "carbs": 32,
    "userId": 9,
    "servingUnit": "medium",
    "quantity": 4,
    "date": "4/27/2018"
  },
  {
    "name": "bacon",
    "sugar": 1,
    "calories": 201,
    "totalFat": 2,
    "sodium": 18,
    "protein": 13,
    "carbs": 37,
    "userId": 7,
    "servingUnit": "",
    "quantity": 1,
    "date": "4/29/2018"
  },
  {
    "name": "grapes",
    "sugar": 29,
    "calories": 114,
    "totalFat": 14,
    "sodium": 103,
    "protein": 15,
    "carbs": 12,
    "userId": 6,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/19/2018"
  },
  {
    "name": "wine",
    "sugar": 28,
    "calories": 68,
    "totalFat": 14,
    "sodium": 2,
    "protein": 2,
    "carbs": 35,
    "userId": 1,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "5/17/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 17,
    "calories": 1,
    "totalFat": 6,
    "sodium": 79,
    "protein": 14,
    "carbs": 18,
    "userId": 3,
    "servingUnit": "gallon",
    "quantity": 3,
    "date": "5/2/2018"
  },
  {
    "name": "orange juice",
    "sugar": 26,
    "calories": 152,
    "totalFat": 17,
    "sodium": 73,
    "protein": 15,
    "carbs": 39,
    "userId": 3,
    "servingUnit": "medium",
    "quantity": 5,
    "date": "5/19/2018"
  },
  {
    "name": "whiskey",
    "sugar": 11,
    "calories": 196,
    "totalFat": 13,
    "sodium": 148,
    "protein": 6,
    "carbs": 2,
    "userId": 2,
    "servingUnit": "small",
    "quantity": 3,
    "date": "4/26/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 28,
    "calories": 93,
    "totalFat": 24,
    "sodium": 6,
    "protein": 6,
    "carbs": 24,
    "userId": 1,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/19/2018"
  },
  {
    "name": "soda",
    "sugar": 7,
    "calories": 155,
    "totalFat": 18,
    "sodium": 72,
    "protein": 4,
    "carbs": 34,
    "userId": 3,
    "servingUnit": "gallon",
    "quantity": 5,
    "date": "4/23/2018"
  },
  {
    "name": "milk",
    "sugar": 6,
    "calories": 29,
    "totalFat": 7,
    "sodium": 24,
    "protein": 8,
    "carbs": 24,
    "userId": 6,
    "servingUnit": "handful",
    "quantity": 5,
    "date": "4/30/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 1,
    "calories": 176,
    "totalFat": 7,
    "sodium": 108,
    "protein": 8,
    "carbs": 17,
    "userId": 9,
    "servingUnit": "lbs",
    "quantity": 4,
    "date": "5/15/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 24,
    "calories": 147,
    "totalFat": 17,
    "sodium": 49,
    "protein": 14,
    "carbs": 22,
    "userId": 8,
    "servingUnit": "cup",
    "quantity": 2,
    "date": "5/14/2018"
  },
  {
    "name": "grapes",
    "sugar": 26,
    "calories": 248,
    "totalFat": 10,
    "sodium": 122,
    "protein": 10,
    "carbs": 46,
    "userId": 1,
    "servingUnit": "cup",
    "quantity": 4,
    "date": "4/23/2018"
  },
  {
    "name": "orange juice",
    "sugar": 12,
    "calories": 114,
    "totalFat": 12,
    "sodium": 2,
    "protein": 7,
    "carbs": 46,
    "userId": 1,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "5/15/2018"
  },
  {
    "name": "grapes",
    "sugar": 1,
    "calories": 244,
    "totalFat": 21,
    "sodium": 45,
    "protein": 4,
    "carbs": 35,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 2,
    "date": "5/4/2018"
  },
  {
    "name": "lasagna",
    "sugar": 28,
    "calories": 32,
    "totalFat": 14,
    "sodium": 17,
    "protein": 13,
    "carbs": 2,
    "userId": 6,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "5/12/2018"
  },
  {
    "name": "pudding",
    "sugar": 5,
    "calories": 275,
    "totalFat": 15,
    "sodium": 93,
    "protein": 8,
    "carbs": 13,
    "userId": 10,
    "servingUnit": "medium",
    "quantity": 5,
    "date": "4/26/2018"
  },
  {
    "name": "cola",
    "sugar": 31,
    "calories": 41,
    "totalFat": 8,
    "sodium": 109,
    "protein": 7,
    "carbs": 29,
    "userId": 10,
    "servingUnit": "lbs",
    "quantity": 2,
    "date": "5/12/2018"
  },
  {
    "name": "cola",
    "sugar": 18,
    "calories": 44,
    "totalFat": 7,
    "sodium": 22,
    "protein": 8,
    "carbs": 15,
    "userId": 8,
    "servingUnit": "cup",
    "quantity": 4,
    "date": "5/1/2018"
  },
  {
    "name": "apple",
    "sugar": 31,
    "calories": 245,
    "totalFat": 18,
    "sodium": 31,
    "protein": 12,
    "carbs": 28,
    "userId": 8,
    "servingUnit": "handful",
    "quantity": 4,
    "date": "5/11/2018"
  },
  {
    "name": "turkey",
    "sugar": 1,
    "calories": 83,
    "totalFat": 22,
    "sodium": 133,
    "protein": 12,
    "carbs": 31,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "5/7/2018"
  },
  {
    "name": "mac'n'cheese",
    "sugar": 5,
    "calories": 222,
    "totalFat": 6,
    "sodium": 131,
    "protein": 1,
    "carbs": 26,
    "userId": 6,
    "servingUnit": "L",
    "quantity": 3,
    "date": "5/4/2018"
  },
  {
    "name": "hot chocolate",
    "sugar": 1,
    "calories": 228,
    "totalFat": 13,
    "sodium": 35,
    "protein": 9,
    "carbs": 38,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/10/2018"
  },
  {
    "name": "meatballs",
    "sugar": 10,
    "calories": 239,
    "totalFat": 23,
    "sodium": 38,
    "protein": 4,
    "carbs": 43,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 4,
    "date": "4/20/2018"
  },
  {
    "name": "yogurt",
    "sugar": 35,
    "calories": 196,
    "totalFat": 21,
    "sodium": 117,
    "protein": 8,
    "carbs": 36,
    "userId": 4,
    "servingUnit": "gallon",
    "quantity": 3,
    "date": "5/8/2018"
  },
  {
    "name": "meatballs",
    "sugar": 11,
    "calories": 246,
    "totalFat": 13,
    "sodium": 113,
    "protein": 5,
    "carbs": 8,
    "userId": 4,
    "servingUnit": "bucket",
    "quantity": 5,
    "date": "5/19/2018"
  },
  {
    "name": "cola",
    "sugar": 32,
    "calories": 282,
    "totalFat": 1,
    "sodium": 104,
    "protein": 5,
    "carbs": 6,
    "userId": 2,
    "servingUnit": "much",
    "quantity": 2,
    "date": "5/19/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 23,
    "calories": 125,
    "totalFat": 7,
    "sodium": 30,
    "protein": 2,
    "carbs": 44,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 4,
    "date": "5/16/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 10,
    "calories": 60,
    "totalFat": 8,
    "sodium": 66,
    "protein": 2,
    "carbs": 3,
    "userId": 10,
    "servingUnit": "L",
    "quantity": 2,
    "date": "5/10/2018"
  },
  {
    "name": "lasagna",
    "sugar": 25,
    "calories": 165,
    "totalFat": 22,
    "sodium": 63,
    "protein": 10,
    "carbs": 27,
    "userId": 10,
    "servingUnit": "handful",
    "quantity": 2,
    "date": "5/13/2018"
  },
  {
    "name": "soda",
    "sugar": 13,
    "calories": 283,
    "totalFat": 18,
    "sodium": 69,
    "protein": 11,
    "carbs": 45,
    "userId": 2,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "5/16/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 5,
    "calories": 63,
    "totalFat": 20,
    "sodium": 13,
    "protein": 15,
    "carbs": 3,
    "userId": 8,
    "servingUnit": "cup",
    "quantity": 4,
    "date": "5/13/2018"
  },
  {
    "name": "shrimp",
    "sugar": 7,
    "calories": 56,
    "totalFat": 17,
    "sodium": 111,
    "protein": 14,
    "carbs": 44,
    "userId": 9,
    "servingUnit": "oz",
    "quantity": 2,
    "date": "5/13/2018"
  },
  {
    "name": "whiskey",
    "sugar": 21,
    "calories": 42,
    "totalFat": 25,
    "sodium": 113,
    "protein": 12,
    "carbs": 47,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 5,
    "date": "5/5/2018"
  },
  {
    "name": "cola",
    "sugar": 9,
    "calories": 146,
    "totalFat": 9,
    "sodium": 138,
    "protein": 10,
    "carbs": 29,
    "userId": 2,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "4/28/2018"
  },
  {
    "name": "whiskey",
    "sugar": 22,
    "calories": 149,
    "totalFat": 16,
    "sodium": 42,
    "protein": 12,
    "carbs": 24,
    "userId": 2,
    "servingUnit": "bucket",
    "quantity": 1,
    "date": "5/16/2018"
  },
  {
    "name": "wine",
    "sugar": 25,
    "calories": 58,
    "totalFat": 21,
    "sodium": 120,
    "protein": 6,
    "carbs": 32,
    "userId": 10,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/16/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 15,
    "calories": 149,
    "totalFat": 10,
    "sodium": 146,
    "protein": 10,
    "carbs": 32,
    "userId": 3,
    "servingUnit": "lbs",
    "quantity": 4,
    "date": "4/25/2018"
  },
  {
    "name": "soda",
    "sugar": 29,
    "calories": 47,
    "totalFat": 13,
    "sodium": 30,
    "protein": 14,
    "carbs": 46,
    "userId": 9,
    "servingUnit": "handful",
    "quantity": 4,
    "date": "5/5/2018"
  },
  {
    "name": "popcorn",
    "sugar": 24,
    "calories": 30,
    "totalFat": 10,
    "sodium": 143,
    "protein": 13,
    "carbs": 41,
    "userId": 10,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "4/22/2018"
  },
  {
    "name": "meatballs",
    "sugar": 29,
    "calories": 13,
    "totalFat": 3,
    "sodium": 15,
    "protein": 1,
    "carbs": 16,
    "userId": 6,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/6/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 35,
    "calories": 210,
    "totalFat": 12,
    "sodium": 71,
    "protein": 15,
    "carbs": 7,
    "userId": 6,
    "servingUnit": "bucket",
    "quantity": 1,
    "date": "4/27/2018"
  },
  {
    "name": "carrots",
    "sugar": 33,
    "calories": 230,
    "totalFat": 19,
    "sodium": 64,
    "protein": 7,
    "carbs": 32,
    "userId": 9,
    "servingUnit": "oz",
    "quantity": 5,
    "date": "5/13/2018"
  },
  {
    "name": "beer",
    "sugar": 10,
    "calories": 86,
    "totalFat": 11,
    "sodium": 123,
    "protein": 7,
    "carbs": 9,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 3,
    "date": "4/28/2018"
  },
  {
    "name": "yogurt",
    "sugar": 9,
    "calories": 25,
    "totalFat": 2,
    "sodium": 114,
    "protein": 15,
    "carbs": 30,
    "userId": 7,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "4/22/2018"
  },
  {
    "name": "milk",
    "sugar": 20,
    "calories": 238,
    "totalFat": 25,
    "sodium": 81,
    "protein": 8,
    "carbs": 20,
    "userId": 1,
    "servingUnit": "bucket",
    "quantity": 5,
    "date": "4/27/2018"
  },
  {
    "name": "orange juice",
    "sugar": 4,
    "calories": 174,
    "totalFat": 6,
    "sodium": 48,
    "protein": 3,
    "carbs": 43,
    "userId": 1,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "5/18/2018"
  },
  {
    "name": "lasagna",
    "sugar": 3,
    "calories": 99,
    "totalFat": 21,
    "sodium": 94,
    "protein": 4,
    "carbs": 2,
    "userId": 3,
    "servingUnit": "oz",
    "quantity": 4,
    "date": "4/23/2018"
  },
  {
    "name": "shrimp",
    "sugar": 9,
    "calories": 119,
    "totalFat": 10,
    "sodium": 125,
    "protein": 2,
    "carbs": 9,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "5/12/2018"
  },
  {
    "name": "meatballs",
    "sugar": 24,
    "calories": 48,
    "totalFat": 16,
    "sodium": 79,
    "protein": 8,
    "carbs": 35,
    "userId": 9,
    "servingUnit": "oz",
    "quantity": 2,
    "date": "5/15/2018"
  },
  {
    "name": "pudding",
    "sugar": 14,
    "calories": 35,
    "totalFat": 21,
    "sodium": 42,
    "protein": 12,
    "carbs": 45,
    "userId": 4,
    "servingUnit": "handful",
    "quantity": 4,
    "date": "4/30/2018"
  },
  {
    "name": "beer",
    "sugar": 1,
    "calories": 17,
    "totalFat": 21,
    "sodium": 21,
    "protein": 11,
    "carbs": 28,
    "userId": 1,
    "servingUnit": "oz",
    "quantity": 2,
    "date": "5/4/2018"
  },
  {
    "name": "whiskey",
    "sugar": 24,
    "calories": 250,
    "totalFat": 7,
    "sodium": 76,
    "protein": 15,
    "carbs": 23,
    "userId": 9,
    "servingUnit": "bucket",
    "quantity": 1,
    "date": "4/25/2018"
  },
  {
    "name": "whiskey",
    "sugar": 33,
    "calories": 54,
    "totalFat": 16,
    "sodium": 60,
    "protein": 3,
    "carbs": 46,
    "userId": 2,
    "servingUnit": "small",
    "quantity": 2,
    "date": "4/26/2018"
  },
  {
    "name": "whiskey",
    "sugar": 23,
    "calories": 285,
    "totalFat": 21,
    "sodium": 70,
    "protein": 14,
    "carbs": 36,
    "userId": 2,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/5/2018"
  },
  {
    "name": "cola",
    "sugar": 10,
    "calories": 24,
    "totalFat": 5,
    "sodium": 65,
    "protein": 15,
    "carbs": 49,
    "userId": 2,
    "servingUnit": "gallon",
    "quantity": 1,
    "date": "5/10/2018"
  },
  {
    "name": "popcorn",
    "sugar": 35,
    "calories": 171,
    "totalFat": 4,
    "sodium": 130,
    "protein": 7,
    "carbs": 48,
    "userId": 6,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "5/8/2018"
  },
  {
    "name": "bacon",
    "sugar": 28,
    "calories": 16,
    "totalFat": 5,
    "sodium": 140,
    "protein": 14,
    "carbs": 12,
    "userId": 6,
    "servingUnit": "oz",
    "quantity": 5,
    "date": "5/16/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 22,
    "calories": 248,
    "totalFat": 20,
    "sodium": 78,
    "protein": 5,
    "carbs": 45,
    "userId": 1,
    "servingUnit": "handful",
    "quantity": 4,
    "date": "4/26/2018"
  },
  {
    "name": "shrimp",
    "sugar": 24,
    "calories": 43,
    "totalFat": 25,
    "sodium": 71,
    "protein": 10,
    "carbs": 21,
    "userId": 4,
    "servingUnit": "medium",
    "quantity": 1,
    "date": "4/27/2018"
  },
  {
    "name": "grapes",
    "sugar": 11,
    "calories": 7,
    "totalFat": 17,
    "sodium": 32,
    "protein": 10,
    "carbs": 26,
    "userId": 5,
    "servingUnit": "gallon",
    "quantity": 2,
    "date": "5/13/2018"
  },
  {
    "name": "coffee",
    "sugar": 5,
    "calories": 247,
    "totalFat": 14,
    "sodium": 74,
    "protein": 15,
    "carbs": 19,
    "userId": 7,
    "servingUnit": "small",
    "quantity": 4,
    "date": "5/16/2018"
  },
  {
    "name": "milk",
    "sugar": 34,
    "calories": 262,
    "totalFat": 25,
    "sodium": 85,
    "protein": 2,
    "carbs": 39,
    "userId": 7,
    "servingUnit": "handful",
    "quantity": 3,
    "date": "4/27/2018"
  },
  {
    "name": "cookie",
    "sugar": 8,
    "calories": 272,
    "totalFat": 16,
    "sodium": 45,
    "protein": 14,
    "carbs": 24,
    "userId": 6,
    "servingUnit": "medium",
    "quantity": 1,
    "date": "4/26/2018"
  },
  {
    "name": "shrimp",
    "sugar": 17,
    "calories": 37,
    "totalFat": 24,
    "sodium": 13,
    "protein": 15,
    "carbs": 44,
    "userId": 3,
    "servingUnit": "L",
    "quantity": 1,
    "date": "5/4/2018"
  },
  {
    "name": "eggs",
    "sugar": 18,
    "calories": 104,
    "totalFat": 22,
    "sodium": 45,
    "protein": 9,
    "carbs": 47,
    "userId": 3,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "5/4/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 15,
    "calories": 118,
    "totalFat": 11,
    "sodium": 81,
    "protein": 5,
    "carbs": 19,
    "userId": 4,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "4/20/2018"
  },
  {
    "name": "carrots",
    "sugar": 19,
    "calories": 16,
    "totalFat": 8,
    "sodium": 5,
    "protein": 8,
    "carbs": 15,
    "userId": 10,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "5/10/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 13,
    "calories": 217,
    "totalFat": 1,
    "sodium": 80,
    "protein": 6,
    "carbs": 15,
    "userId": 8,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "5/11/2018"
  },
  {
    "name": "eggs",
    "sugar": 13,
    "calories": 296,
    "totalFat": 3,
    "sodium": 30,
    "protein": 12,
    "carbs": 2,
    "userId": 6,
    "servingUnit": "bucket",
    "quantity": 5,
    "date": "5/18/2018"
  },
  {
    "name": "toast",
    "sugar": 24,
    "calories": 246,
    "totalFat": 9,
    "sodium": 21,
    "protein": 3,
    "carbs": 34,
    "userId": 1,
    "servingUnit": "much",
    "quantity": 2,
    "date": "5/18/2018"
  },
  {
    "name": "toast",
    "sugar": 18,
    "calories": 124,
    "totalFat": 15,
    "sodium": 71,
    "protein": 15,
    "carbs": 9,
    "userId": 7,
    "servingUnit": "gallon",
    "quantity": 3,
    "date": "5/4/2018"
  },
  {
    "name": "sausage",
    "sugar": 10,
    "calories": 255,
    "totalFat": 14,
    "sodium": 84,
    "protein": 5,
    "carbs": 16,
    "userId": 1,
    "servingUnit": "cup",
    "quantity": 5,
    "date": "4/25/2018"
  },
  {
    "name": "cola",
    "sugar": 16,
    "calories": 280,
    "totalFat": 22,
    "sodium": 76,
    "protein": 8,
    "carbs": 12,
    "userId": 5,
    "servingUnit": "gallon",
    "quantity": 1,
    "date": "5/15/2018"
  },
  {
    "name": "shrimp",
    "sugar": 13,
    "calories": 276,
    "totalFat": 12,
    "sodium": 109,
    "protein": 8,
    "carbs": 47,
    "userId": 9,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "5/4/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 25,
    "calories": 249,
    "totalFat": 16,
    "sodium": 80,
    "protein": 6,
    "carbs": 34,
    "userId": 7,
    "servingUnit": "small",
    "quantity": 4,
    "date": "5/9/2018"
  },
  {
    "name": "grapes",
    "sugar": 23,
    "calories": 231,
    "totalFat": 6,
    "sodium": 4,
    "protein": 2,
    "carbs": 31,
    "userId": 8,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "5/7/2018"
  },
  {
    "name": "soda",
    "sugar": 3,
    "calories": 170,
    "totalFat": 25,
    "sodium": 58,
    "protein": 8,
    "carbs": 3,
    "userId": 1,
    "servingUnit": "handful",
    "quantity": 5,
    "date": "4/27/2018"
  },
  {
    "name": "eggs",
    "sugar": 30,
    "calories": 126,
    "totalFat": 19,
    "sodium": 41,
    "protein": 10,
    "carbs": 42,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "5/18/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 34,
    "calories": 280,
    "totalFat": 22,
    "sodium": 95,
    "protein": 11,
    "carbs": 2,
    "userId": 8,
    "servingUnit": "L",
    "quantity": 4,
    "date": "4/25/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 26,
    "calories": 121,
    "totalFat": 19,
    "sodium": 19,
    "protein": 8,
    "carbs": 11,
    "userId": 7,
    "servingUnit": "L",
    "quantity": 3,
    "date": "5/19/2018"
  },
  {
    "name": "hot chocolate",
    "sugar": 22,
    "calories": 251,
    "totalFat": 5,
    "sodium": 16,
    "protein": 11,
    "carbs": 34,
    "userId": 3,
    "servingUnit": "",
    "quantity": 1,
    "date": "4/21/2018"
  },
  {
    "name": "yogurt",
    "sugar": 12,
    "calories": 137,
    "totalFat": 23,
    "sodium": 79,
    "protein": 12,
    "carbs": 3,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 4,
    "date": "5/1/2018"
  },
  {
    "name": "orange juice",
    "sugar": 19,
    "calories": 191,
    "totalFat": 10,
    "sodium": 53,
    "protein": 14,
    "carbs": 45,
    "userId": 6,
    "servingUnit": "L",
    "quantity": 5,
    "date": "5/16/2018"
  },
  {
    "name": "pork-chops",
    "sugar": 32,
    "calories": 34,
    "totalFat": 20,
    "sodium": 4,
    "protein": 2,
    "carbs": 5,
    "userId": 5,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "4/22/2018"
  },
  {
    "name": "grapes",
    "sugar": 20,
    "calories": 224,
    "totalFat": 25,
    "sodium": 87,
    "protein": 5,
    "carbs": 16,
    "userId": 6,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "5/6/2018"
  },
  {
    "name": "beer",
    "sugar": 13,
    "calories": 73,
    "totalFat": 3,
    "sodium": 97,
    "protein": 9,
    "carbs": 37,
    "userId": 1,
    "servingUnit": "much",
    "quantity": 5,
    "date": "4/20/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 1,
    "calories": 215,
    "totalFat": 9,
    "sodium": 44,
    "protein": 11,
    "carbs": 42,
    "userId": 4,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "5/11/2018"
  },
  {
    "name": "popcorn",
    "sugar": 14,
    "calories": 36,
    "totalFat": 13,
    "sodium": 135,
    "protein": 4,
    "carbs": 30,
    "userId": 7,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "4/28/2018"
  },
  {
    "name": "popcorn",
    "sugar": 14,
    "calories": 205,
    "totalFat": 14,
    "sodium": 83,
    "protein": 7,
    "carbs": 34,
    "userId": 10,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "4/23/2018"
  },
  {
    "name": "beer",
    "sugar": 32,
    "calories": 111,
    "totalFat": 5,
    "sodium": 116,
    "protein": 2,
    "carbs": 35,
    "userId": 3,
    "servingUnit": "much",
    "quantity": 1,
    "date": "5/14/2018"
  },
  {
    "name": "mac'n'cheese",
    "sugar": 24,
    "calories": 111,
    "totalFat": 12,
    "sodium": 146,
    "protein": 8,
    "carbs": 40,
    "userId": 6,
    "servingUnit": "",
    "quantity": 2,
    "date": "5/11/2018"
  },
  {
    "name": "cookie",
    "sugar": 33,
    "calories": 244,
    "totalFat": 24,
    "sodium": 16,
    "protein": 9,
    "carbs": 24,
    "userId": 4,
    "servingUnit": "",
    "quantity": 5,
    "date": "5/1/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 24,
    "calories": 283,
    "totalFat": 7,
    "sodium": 86,
    "protein": 9,
    "carbs": 30,
    "userId": 2,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "5/16/2018"
  },
  {
    "name": "cola",
    "sugar": 12,
    "calories": 263,
    "totalFat": 24,
    "sodium": 20,
    "protein": 2,
    "carbs": 28,
    "userId": 1,
    "servingUnit": "medium",
    "quantity": 1,
    "date": "5/19/2018"
  },
  {
    "name": "meatballs",
    "sugar": 25,
    "calories": 258,
    "totalFat": 3,
    "sodium": 47,
    "protein": 1,
    "carbs": 17,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 1,
    "date": "5/4/2018"
  },
  {
    "name": "soda",
    "sugar": 32,
    "calories": 224,
    "totalFat": 3,
    "sodium": 111,
    "protein": 12,
    "carbs": 14,
    "userId": 7,
    "servingUnit": "much",
    "quantity": 1,
    "date": "4/20/2018"
  },
  {
    "name": "cookie",
    "sugar": 3,
    "calories": 236,
    "totalFat": 24,
    "sodium": 62,
    "protein": 3,
    "carbs": 16,
    "userId": 10,
    "servingUnit": "",
    "quantity": 4,
    "date": "4/25/2018"
  },
  {
    "name": "apple",
    "sugar": 24,
    "calories": 162,
    "totalFat": 3,
    "sodium": 125,
    "protein": 9,
    "carbs": 18,
    "userId": 9,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "4/23/2018"
  },
  {
    "name": "bacon",
    "sugar": 33,
    "calories": 232,
    "totalFat": 14,
    "sodium": 124,
    "protein": 12,
    "carbs": 18,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 3,
    "date": "5/4/2018"
  },
  {
    "name": "cookie",
    "sugar": 27,
    "calories": 14,
    "totalFat": 10,
    "sodium": 59,
    "protein": 15,
    "carbs": 38,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 2,
    "date": "4/29/2018"
  },
  {
    "name": "coffee",
    "sugar": 35,
    "calories": 182,
    "totalFat": 18,
    "sodium": 107,
    "protein": 7,
    "carbs": 50,
    "userId": 10,
    "servingUnit": "much",
    "quantity": 2,
    "date": "5/9/2018"
  },
  {
    "name": "toast",
    "sugar": 23,
    "calories": 21,
    "totalFat": 18,
    "sodium": 21,
    "protein": 1,
    "carbs": 46,
    "userId": 2,
    "servingUnit": "L",
    "quantity": 2,
    "date": "5/12/2018"
  },
  {
    "name": "hot chocolate",
    "sugar": 13,
    "calories": 300,
    "totalFat": 16,
    "sodium": 128,
    "protein": 3,
    "carbs": 38,
    "userId": 6,
    "servingUnit": "oz",
    "quantity": 5,
    "date": "5/2/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 18,
    "calories": 140,
    "totalFat": 13,
    "sodium": 45,
    "protein": 11,
    "carbs": 19,
    "userId": 1,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "4/23/2018"
  },
  {
    "name": "grapes",
    "sugar": 33,
    "calories": 61,
    "totalFat": 20,
    "sodium": 71,
    "protein": 13,
    "carbs": 36,
    "userId": 1,
    "servingUnit": "",
    "quantity": 2,
    "date": "4/24/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 19,
    "calories": 139,
    "totalFat": 11,
    "sodium": 127,
    "protein": 12,
    "carbs": 16,
    "userId": 5,
    "servingUnit": "L",
    "quantity": 4,
    "date": "5/12/2018"
  },
  {
    "name": "sausage",
    "sugar": 9,
    "calories": 126,
    "totalFat": 13,
    "sodium": 104,
    "protein": 7,
    "carbs": 6,
    "userId": 10,
    "servingUnit": "L",
    "quantity": 1,
    "date": "4/29/2018"
  },
  {
    "name": "meatballs",
    "sugar": 11,
    "calories": 3,
    "totalFat": 22,
    "sodium": 13,
    "protein": 8,
    "carbs": 15,
    "userId": 4,
    "servingUnit": "much",
    "quantity": 2,
    "date": "4/23/2018"
  },
  {
    "name": "popcorn",
    "sugar": 27,
    "calories": 39,
    "totalFat": 21,
    "sodium": 100,
    "protein": 6,
    "carbs": 18,
    "userId": 8,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/17/2018"
  },
  {
    "name": "turkey",
    "sugar": 12,
    "calories": 300,
    "totalFat": 18,
    "sodium": 113,
    "protein": 4,
    "carbs": 14,
    "userId": 8,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/7/2018"
  },
  {
    "name": "sausage",
    "sugar": 2,
    "calories": 246,
    "totalFat": 2,
    "sodium": 124,
    "protein": 10,
    "carbs": 40,
    "userId": 1,
    "servingUnit": "gallon",
    "quantity": 5,
    "date": "5/3/2018"
  },
  {
    "name": "milk",
    "sugar": 1,
    "calories": 7,
    "totalFat": 25,
    "sodium": 27,
    "protein": 15,
    "carbs": 11,
    "userId": 9,
    "servingUnit": "gallon",
    "quantity": 2,
    "date": "5/4/2018"
  },
  {
    "name": "pudding",
    "sugar": 33,
    "calories": 133,
    "totalFat": 23,
    "sodium": 117,
    "protein": 15,
    "carbs": 5,
    "userId": 8,
    "servingUnit": "small",
    "quantity": 2,
    "date": "5/18/2018"
  },
  {
    "name": "pork-chops",
    "sugar": 1,
    "calories": 17,
    "totalFat": 17,
    "sodium": 18,
    "protein": 2,
    "carbs": 8,
    "userId": 4,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "5/13/2018"
  },
  {
    "name": "soda",
    "sugar": 31,
    "calories": 132,
    "totalFat": 25,
    "sodium": 14,
    "protein": 2,
    "carbs": 31,
    "userId": 3,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "4/28/2018"
  },
  {
    "name": "lasagna",
    "sugar": 29,
    "calories": 105,
    "totalFat": 15,
    "sodium": 142,
    "protein": 8,
    "carbs": 12,
    "userId": 6,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "4/28/2018"
  },
  {
    "name": "grapes",
    "sugar": 29,
    "calories": 230,
    "totalFat": 5,
    "sodium": 142,
    "protein": 5,
    "carbs": 30,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 2,
    "date": "5/14/2018"
  },
  {
    "name": "pudding",
    "sugar": 35,
    "calories": 25,
    "totalFat": 20,
    "sodium": 67,
    "protein": 13,
    "carbs": 27,
    "userId": 10,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "4/23/2018"
  },
  {
    "name": "beer",
    "sugar": 10,
    "calories": 204,
    "totalFat": 12,
    "sodium": 9,
    "protein": 15,
    "carbs": 25,
    "userId": 10,
    "servingUnit": "bucket",
    "quantity": 3,
    "date": "5/1/2018"
  },
  {
    "name": "turkey",
    "sugar": 17,
    "calories": 69,
    "totalFat": 1,
    "sodium": 39,
    "protein": 5,
    "carbs": 46,
    "userId": 3,
    "servingUnit": "",
    "quantity": 3,
    "date": "5/4/2018"
  },
  {
    "name": "hot chocolate",
    "sugar": 30,
    "calories": 53,
    "totalFat": 7,
    "sodium": 150,
    "protein": 7,
    "carbs": 3,
    "userId": 7,
    "servingUnit": "handful",
    "quantity": 2,
    "date": "5/14/2018"
  },
  {
    "name": "apple",
    "sugar": 3,
    "calories": 110,
    "totalFat": 15,
    "sodium": 61,
    "protein": 15,
    "carbs": 39,
    "userId": 10,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "4/20/2018"
  },
  {
    "name": "wine",
    "sugar": 8,
    "calories": 95,
    "totalFat": 5,
    "sodium": 33,
    "protein": 11,
    "carbs": 26,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 5,
    "date": "4/30/2018"
  },
  {
    "name": "meatballs",
    "sugar": 27,
    "calories": 166,
    "totalFat": 2,
    "sodium": 128,
    "protein": 9,
    "carbs": 9,
    "userId": 10,
    "servingUnit": "L",
    "quantity": 1,
    "date": "5/7/2018"
  },
  {
    "name": "grapes",
    "sugar": 19,
    "calories": 122,
    "totalFat": 24,
    "sodium": 41,
    "protein": 9,
    "carbs": 6,
    "userId": 10,
    "servingUnit": "oz",
    "quantity": 3,
    "date": "4/23/2018"
  },
  {
    "name": "cookie",
    "sugar": 27,
    "calories": 55,
    "totalFat": 12,
    "sodium": 94,
    "protein": 6,
    "carbs": 32,
    "userId": 9,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/7/2018"
  },
  {
    "name": "orange juice",
    "sugar": 21,
    "calories": 197,
    "totalFat": 23,
    "sodium": 136,
    "protein": 12,
    "carbs": 10,
    "userId": 6,
    "servingUnit": "small",
    "quantity": 1,
    "date": "5/19/2018"
  },
  {
    "name": "orange juice",
    "sugar": 11,
    "calories": 59,
    "totalFat": 13,
    "sodium": 31,
    "protein": 12,
    "carbs": 34,
    "userId": 7,
    "servingUnit": "bucket",
    "quantity": 3,
    "date": "5/12/2018"
  },
  {
    "name": "beer",
    "sugar": 18,
    "calories": 158,
    "totalFat": 23,
    "sodium": 24,
    "protein": 3,
    "carbs": 5,
    "userId": 9,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "5/14/2018"
  },
  {
    "name": "yogurt",
    "sugar": 5,
    "calories": 270,
    "totalFat": 12,
    "sodium": 39,
    "protein": 14,
    "carbs": 5,
    "userId": 7,
    "servingUnit": "cup",
    "quantity": 2,
    "date": "5/2/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 11,
    "calories": 258,
    "totalFat": 12,
    "sodium": 110,
    "protein": 11,
    "carbs": 15,
    "userId": 5,
    "servingUnit": "oz",
    "quantity": 2,
    "date": "4/24/2018"
  },
  {
    "name": "soda",
    "sugar": 21,
    "calories": 79,
    "totalFat": 23,
    "sodium": 22,
    "protein": 7,
    "carbs": 11,
    "userId": 5,
    "servingUnit": "",
    "quantity": 5,
    "date": "5/7/2018"
  },
  {
    "name": "sausage",
    "sugar": 17,
    "calories": 110,
    "totalFat": 7,
    "sodium": 104,
    "protein": 7,
    "carbs": 49,
    "userId": 5,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "4/21/2018"
  },
  {
    "name": "mac'n'cheese",
    "sugar": 34,
    "calories": 210,
    "totalFat": 7,
    "sodium": 89,
    "protein": 13,
    "carbs": 23,
    "userId": 8,
    "servingUnit": "L",
    "quantity": 2,
    "date": "5/17/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 15,
    "calories": 120,
    "totalFat": 15,
    "sodium": 47,
    "protein": 15,
    "carbs": 4,
    "userId": 5,
    "servingUnit": "L",
    "quantity": 2,
    "date": "4/26/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 14,
    "calories": 210,
    "totalFat": 22,
    "sodium": 103,
    "protein": 2,
    "carbs": 47,
    "userId": 10,
    "servingUnit": "cup",
    "quantity": 5,
    "date": "4/28/2018"
  },
  {
    "name": "wine",
    "sugar": 13,
    "calories": 118,
    "totalFat": 6,
    "sodium": 111,
    "protein": 3,
    "carbs": 29,
    "userId": 1,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "4/25/2018"
  },
  {
    "name": "pudding",
    "sugar": 18,
    "calories": 170,
    "totalFat": 6,
    "sodium": 47,
    "protein": 6,
    "carbs": 43,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 2,
    "date": "5/12/2018"
  },
  {
    "name": "grapes",
    "sugar": 11,
    "calories": 153,
    "totalFat": 13,
    "sodium": 143,
    "protein": 8,
    "carbs": 10,
    "userId": 10,
    "servingUnit": "gallon",
    "quantity": 2,
    "date": "4/28/2018"
  },
  {
    "name": "orange juice",
    "sugar": 14,
    "calories": 262,
    "totalFat": 20,
    "sodium": 33,
    "protein": 14,
    "carbs": 45,
    "userId": 8,
    "servingUnit": "gallon",
    "quantity": 1,
    "date": "5/4/2018"
  },
  {
    "name": "shrimp",
    "sugar": 12,
    "calories": 219,
    "totalFat": 8,
    "sodium": 134,
    "protein": 4,
    "carbs": 6,
    "userId": 8,
    "servingUnit": "much",
    "quantity": 4,
    "date": "4/26/2018"
  },
  {
    "name": "shrimp",
    "sugar": 24,
    "calories": 213,
    "totalFat": 11,
    "sodium": 150,
    "protein": 7,
    "carbs": 41,
    "userId": 8,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "4/20/2018"
  },
  {
    "name": "wine",
    "sugar": 20,
    "calories": 200,
    "totalFat": 25,
    "sodium": 87,
    "protein": 15,
    "carbs": 3,
    "userId": 10,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "4/24/2018"
  },
  {
    "name": "milk",
    "sugar": 7,
    "calories": 40,
    "totalFat": 17,
    "sodium": 27,
    "protein": 9,
    "carbs": 24,
    "userId": 1,
    "servingUnit": "medium",
    "quantity": 1,
    "date": "5/12/2018"
  },
  {
    "name": "beer",
    "sugar": 10,
    "calories": 239,
    "totalFat": 24,
    "sodium": 36,
    "protein": 9,
    "carbs": 4,
    "userId": 1,
    "servingUnit": "",
    "quantity": 3,
    "date": "5/10/2018"
  },
  {
    "name": "whiskey",
    "sugar": 30,
    "calories": 125,
    "totalFat": 11,
    "sodium": 46,
    "protein": 13,
    "carbs": 30,
    "userId": 5,
    "servingUnit": "oz",
    "quantity": 2,
    "date": "5/17/2018"
  },
  {
    "name": "cookie",
    "sugar": 28,
    "calories": 209,
    "totalFat": 2,
    "sodium": 19,
    "protein": 5,
    "carbs": 13,
    "userId": 2,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "5/9/2018"
  },
  {
    "name": "cookie",
    "sugar": 17,
    "calories": 193,
    "totalFat": 14,
    "sodium": 31,
    "protein": 12,
    "carbs": 11,
    "userId": 7,
    "servingUnit": "L",
    "quantity": 3,
    "date": "5/9/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 22,
    "calories": 163,
    "totalFat": 4,
    "sodium": 46,
    "protein": 6,
    "carbs": 44,
    "userId": 4,
    "servingUnit": "much",
    "quantity": 1,
    "date": "4/28/2018"
  },
  {
    "name": "pork-chops",
    "sugar": 3,
    "calories": 247,
    "totalFat": 25,
    "sodium": 85,
    "protein": 1,
    "carbs": 33,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 5,
    "date": "5/8/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 4,
    "calories": 148,
    "totalFat": 10,
    "sodium": 117,
    "protein": 4,
    "carbs": 14,
    "userId": 9,
    "servingUnit": "",
    "quantity": 5,
    "date": "5/16/2018"
  },
  {
    "name": "wine",
    "sugar": 33,
    "calories": 209,
    "totalFat": 2,
    "sodium": 32,
    "protein": 10,
    "carbs": 3,
    "userId": 5,
    "servingUnit": "L",
    "quantity": 4,
    "date": "4/23/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 12,
    "calories": 209,
    "totalFat": 15,
    "sodium": 35,
    "protein": 13,
    "carbs": 40,
    "userId": 3,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "4/24/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 35,
    "calories": 87,
    "totalFat": 12,
    "sodium": 53,
    "protein": 14,
    "carbs": 40,
    "userId": 5,
    "servingUnit": "small",
    "quantity": 5,
    "date": "5/19/2018"
  },
  {
    "name": "milk",
    "sugar": 1,
    "calories": 92,
    "totalFat": 6,
    "sodium": 3,
    "protein": 14,
    "carbs": 6,
    "userId": 8,
    "servingUnit": "gallon",
    "quantity": 1,
    "date": "5/10/2018"
  },
  {
    "name": "shrimp",
    "sugar": 27,
    "calories": 165,
    "totalFat": 1,
    "sodium": 83,
    "protein": 6,
    "carbs": 20,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 1,
    "date": "5/4/2018"
  },
  {
    "name": "wine",
    "sugar": 10,
    "calories": 12,
    "totalFat": 23,
    "sodium": 141,
    "protein": 15,
    "carbs": 11,
    "userId": 3,
    "servingUnit": "much",
    "quantity": 1,
    "date": "5/15/2018"
  },
  {
    "name": "soda",
    "sugar": 18,
    "calories": 216,
    "totalFat": 4,
    "sodium": 77,
    "protein": 14,
    "carbs": 44,
    "userId": 6,
    "servingUnit": "oz",
    "quantity": 1,
    "date": "4/25/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 23,
    "calories": 131,
    "totalFat": 24,
    "sodium": 16,
    "protein": 12,
    "carbs": 42,
    "userId": 4,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "5/18/2018"
  },
  {
    "name": "coffee",
    "sugar": 3,
    "calories": 188,
    "totalFat": 21,
    "sodium": 70,
    "protein": 9,
    "carbs": 48,
    "userId": 4,
    "servingUnit": "much",
    "quantity": 5,
    "date": "4/24/2018"
  },
  {
    "name": "wine",
    "sugar": 7,
    "calories": 195,
    "totalFat": 3,
    "sodium": 62,
    "protein": 4,
    "carbs": 16,
    "userId": 1,
    "servingUnit": "much",
    "quantity": 4,
    "date": "5/2/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 20,
    "calories": 96,
    "totalFat": 25,
    "sodium": 13,
    "protein": 1,
    "carbs": 6,
    "userId": 8,
    "servingUnit": "",
    "quantity": 4,
    "date": "4/23/2018"
  },
  {
    "name": "apple",
    "sugar": 13,
    "calories": 116,
    "totalFat": 13,
    "sodium": 134,
    "protein": 1,
    "carbs": 9,
    "userId": 2,
    "servingUnit": "cup",
    "quantity": 1,
    "date": "4/22/2018"
  },
  {
    "name": "milk",
    "sugar": 32,
    "calories": 140,
    "totalFat": 20,
    "sodium": 80,
    "protein": 4,
    "carbs": 42,
    "userId": 9,
    "servingUnit": "lbs",
    "quantity": 4,
    "date": "4/25/2018"
  },
  {
    "name": "pork-chops",
    "sugar": 7,
    "calories": 292,
    "totalFat": 7,
    "sodium": 74,
    "protein": 4,
    "carbs": 40,
    "userId": 9,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "4/29/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 28,
    "calories": 223,
    "totalFat": 4,
    "sodium": 71,
    "protein": 3,
    "carbs": 8,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/16/2018"
  },
  {
    "name": "cola",
    "sugar": 6,
    "calories": 164,
    "totalFat": 13,
    "sodium": 3,
    "protein": 8,
    "carbs": 22,
    "userId": 7,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/5/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 1,
    "calories": 261,
    "totalFat": 15,
    "sodium": 101,
    "protein": 3,
    "carbs": 21,
    "userId": 6,
    "servingUnit": "L",
    "quantity": 2,
    "date": "5/5/2018"
  },
  {
    "name": "soda",
    "sugar": 20,
    "calories": 180,
    "totalFat": 23,
    "sodium": 25,
    "protein": 11,
    "carbs": 22,
    "userId": 8,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/8/2018"
  },
  {
    "name": "beer",
    "sugar": 32,
    "calories": 15,
    "totalFat": 6,
    "sodium": 38,
    "protein": 13,
    "carbs": 21,
    "userId": 8,
    "servingUnit": "L",
    "quantity": 2,
    "date": "5/15/2018"
  },
  {
    "name": "orange juice",
    "sugar": 8,
    "calories": 272,
    "totalFat": 21,
    "sodium": 12,
    "protein": 10,
    "carbs": 41,
    "userId": 1,
    "servingUnit": "handful",
    "quantity": 3,
    "date": "5/9/2018"
  },
  {
    "name": "coffee",
    "sugar": 21,
    "calories": 207,
    "totalFat": 8,
    "sodium": 85,
    "protein": 10,
    "carbs": 47,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 5,
    "date": "5/11/2018"
  },
  {
    "name": "orange juice",
    "sugar": 16,
    "calories": 247,
    "totalFat": 18,
    "sodium": 29,
    "protein": 7,
    "carbs": 44,
    "userId": 6,
    "servingUnit": "gallon",
    "quantity": 3,
    "date": "5/13/2018"
  },
  {
    "name": "eggs",
    "sugar": 34,
    "calories": 78,
    "totalFat": 24,
    "sodium": 97,
    "protein": 11,
    "carbs": 37,
    "userId": 9,
    "servingUnit": "bucket",
    "quantity": 2,
    "date": "5/8/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 18,
    "calories": 180,
    "totalFat": 13,
    "sodium": 117,
    "protein": 7,
    "carbs": 46,
    "userId": 2,
    "servingUnit": "small",
    "quantity": 1,
    "date": "5/12/2018"
  },
  {
    "name": "apple",
    "sugar": 31,
    "calories": 279,
    "totalFat": 3,
    "sodium": 150,
    "protein": 10,
    "carbs": 40,
    "userId": 3,
    "servingUnit": "medium",
    "quantity": 5,
    "date": "4/20/2018"
  },
  {
    "name": "lasagna",
    "sugar": 19,
    "calories": 165,
    "totalFat": 18,
    "sodium": 115,
    "protein": 4,
    "carbs": 29,
    "userId": 5,
    "servingUnit": "handful",
    "quantity": 5,
    "date": "4/20/2018"
  },
  {
    "name": "cola",
    "sugar": 3,
    "calories": 272,
    "totalFat": 22,
    "sodium": 67,
    "protein": 3,
    "carbs": 27,
    "userId": 1,
    "servingUnit": "much",
    "quantity": 1,
    "date": "5/2/2018"
  },
  {
    "name": "bacon",
    "sugar": 22,
    "calories": 130,
    "totalFat": 7,
    "sodium": 69,
    "protein": 8,
    "carbs": 19,
    "userId": 5,
    "servingUnit": "strips",
    "quantity": 3,
    "date": "5/13/2018"
  },
  {
    "name": "ribs",
    "sugar": 29,
    "calories": 97,
    "totalFat": 7,
    "sodium": 68,
    "protein": 7,
    "carbs": 17,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 5,
    "date": "5/12/2018"
  },
  {
    "name": "grapes",
    "sugar": 26,
    "calories": 182,
    "totalFat": 14,
    "sodium": 139,
    "protein": 2,
    "carbs": 23,
    "userId": 3,
    "servingUnit": "handful",
    "quantity": 5,
    "date": "5/7/2018"
  },
  {
    "name": "apple",
    "sugar": 4,
    "calories": 59,
    "totalFat": 3,
    "sodium": 147,
    "protein": 10,
    "carbs": 42,
    "userId": 3,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/19/2018"
  },
  {
    "name": "soda",
    "sugar": 34,
    "calories": 240,
    "totalFat": 24,
    "sodium": 99,
    "protein": 15,
    "carbs": 23,
    "userId": 6,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "5/3/2018"
  },
  {
    "name": "whiskey",
    "sugar": 19,
    "calories": 111,
    "totalFat": 1,
    "sodium": 101,
    "protein": 7,
    "carbs": 22,
    "userId": 3,
    "servingUnit": "gallon",
    "quantity": 2,
    "date": "5/19/2018"
  },
  {
    "name": "lasagna",
    "sugar": 17,
    "calories": 250,
    "totalFat": 21,
    "sodium": 56,
    "protein": 11,
    "carbs": 27,
    "userId": 10,
    "servingUnit": "lbs",
    "quantity": 1,
    "date": "5/7/2018"
  },
  {
    "name": "soda",
    "sugar": 32,
    "calories": 178,
    "totalFat": 25,
    "sodium": 58,
    "protein": 5,
    "carbs": 33,
    "userId": 6,
    "servingUnit": "cup",
    "quantity": 1,
    "date": "5/8/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 31,
    "calories": 231,
    "totalFat": 8,
    "sodium": 71,
    "protein": 7,
    "carbs": 30,
    "userId": 4,
    "servingUnit": "lbs",
    "quantity": 2,
    "date": "5/17/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 19,
    "calories": 235,
    "totalFat": 21,
    "sodium": 82,
    "protein": 6,
    "carbs": 14,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 2,
    "date": "4/25/2018"
  },
  {
    "name": "mac'n'cheese",
    "sugar": 25,
    "calories": 153,
    "totalFat": 17,
    "sodium": 56,
    "protein": 2,
    "carbs": 1,
    "userId": 4,
    "servingUnit": "gallon",
    "quantity": 3,
    "date": "5/12/2018"
  },
  {
    "name": "soda",
    "sugar": 19,
    "calories": 91,
    "totalFat": 15,
    "sodium": 149,
    "protein": 15,
    "carbs": 44,
    "userId": 4,
    "servingUnit": "cup",
    "quantity": 4,
    "date": "5/6/2018"
  },
  {
    "name": "cake",
    "sugar": 27,
    "calories": 86,
    "totalFat": 12,
    "sodium": 92,
    "protein": 4,
    "carbs": 48,
    "userId": 1,
    "servingUnit": "oz",
    "quantity": 4,
    "date": "4/30/2018"
  },
  {
    "name": "popcorn",
    "sugar": 30,
    "calories": 20,
    "totalFat": 15,
    "sodium": 103,
    "protein": 6,
    "carbs": 25,
    "userId": 10,
    "servingUnit": "bucket",
    "quantity": 5,
    "date": "5/16/2018"
  },
  {
    "name": "cookie",
    "sugar": 4,
    "calories": 24,
    "totalFat": 23,
    "sodium": 134,
    "protein": 10,
    "carbs": 42,
    "userId": 1,
    "servingUnit": "L",
    "quantity": 4,
    "date": "4/30/2018"
  },
  {
    "name": "meatballs",
    "sugar": 10,
    "calories": 54,
    "totalFat": 19,
    "sodium": 102,
    "protein": 4,
    "carbs": 9,
    "userId": 2,
    "servingUnit": "medium",
    "quantity": 2,
    "date": "5/13/2018"
  },
  {
    "name": "cake",
    "sugar": 24,
    "calories": 70,
    "totalFat": 13,
    "sodium": 72,
    "protein": 4,
    "carbs": 2,
    "userId": 10,
    "servingUnit": "bucket",
    "quantity": 3,
    "date": "5/12/2018"
  },
  {
    "name": "bacon",
    "sugar": 19,
    "calories": 195,
    "totalFat": 14,
    "sodium": 117,
    "protein": 14,
    "carbs": 8,
    "userId": 4,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "4/23/2018"
  },
  {
    "name": "bacon",
    "sugar": 8,
    "calories": 63,
    "totalFat": 7,
    "sodium": 31,
    "protein": 1,
    "carbs": 47,
    "userId": 7,
    "servingUnit": "oz",
    "quantity": 2,
    "date": "4/30/2018"
  },
  {
    "name": "apple",
    "sugar": 25,
    "calories": 31,
    "totalFat": 6,
    "sodium": 35,
    "protein": 14,
    "carbs": 39,
    "userId": 4,
    "servingUnit": "medium",
    "quantity": 3,
    "date": "5/6/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 30,
    "calories": 91,
    "totalFat": 11,
    "sodium": 128,
    "protein": 4,
    "carbs": 8,
    "userId": 10,
    "servingUnit": "slice",
    "quantity": 5,
    "date": "4/20/2018"
  },
  {
    "name": "ham sandwich",
    "sugar": 29,
    "calories": 88,
    "totalFat": 23,
    "sodium": 48,
    "protein": 12,
    "carbs": 2,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 4,
    "date": "4/22/2018"
  },
  {
    "name": "cola",
    "sugar": 15,
    "calories": 206,
    "totalFat": 17,
    "sodium": 82,
    "protein": 14,
    "carbs": 22,
    "userId": 5,
    "servingUnit": "medium",
    "quantity": 4,
    "date": "5/11/2018"
  },
  {
    "name": "beer",
    "sugar": 28,
    "calories": 35,
    "totalFat": 18,
    "sodium": 81,
    "protein": 6,
    "carbs": 15,
    "userId": 2,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "5/3/2018"
  },
  {
    "name": "lasagna",
    "sugar": 6,
    "calories": 18,
    "totalFat": 12,
    "sodium": 29,
    "protein": 12,
    "carbs": 42,
    "userId": 8,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "4/24/2018"
  },
  {
    "name": "wine",
    "sugar": 12,
    "calories": 147,
    "totalFat": 10,
    "sodium": 18,
    "protein": 2,
    "carbs": 20,
    "userId": 9,
    "servingUnit": "L",
    "quantity": 3,
    "date": "5/7/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 1,
    "calories": 266,
    "totalFat": 17,
    "sodium": 15,
    "protein": 11,
    "carbs": 25,
    "userId": 1,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/7/2018"
  },
  {
    "name": "carrots",
    "sugar": 30,
    "calories": 239,
    "totalFat": 13,
    "sodium": 60,
    "protein": 14,
    "carbs": 3,
    "userId": 9,
    "servingUnit": "much",
    "quantity": 3,
    "date": "5/2/2018"
  },
  {
    "name": "pudding",
    "sugar": 13,
    "calories": 10,
    "totalFat": 14,
    "sodium": 24,
    "protein": 10,
    "carbs": 43,
    "userId": 5,
    "servingUnit": "L",
    "quantity": 4,
    "date": "5/10/2018"
  },
  {
    "name": "wine",
    "sugar": 6,
    "calories": 250,
    "totalFat": 9,
    "sodium": 6,
    "protein": 12,
    "carbs": 36,
    "userId": 3,
    "servingUnit": "gallon",
    "quantity": 3,
    "date": "4/25/2018"
  },
  {
    "name": "soda",
    "sugar": 28,
    "calories": 78,
    "totalFat": 13,
    "sodium": 103,
    "protein": 3,
    "carbs": 6,
    "userId": 4,
    "servingUnit": "",
    "quantity": 1,
    "date": "5/9/2018"
  },
  {
    "name": "popcorn",
    "sugar": 29,
    "calories": 92,
    "totalFat": 24,
    "sodium": 80,
    "protein": 8,
    "carbs": 27,
    "userId": 10,
    "servingUnit": "cup",
    "quantity": 3,
    "date": "4/26/2018"
  },
  {
    "name": "lasagna",
    "sugar": 17,
    "calories": 265,
    "totalFat": 20,
    "sodium": 44,
    "protein": 14,
    "carbs": 6,
    "userId": 5,
    "servingUnit": "gallon",
    "quantity": 2,
    "date": "5/15/2018"
  },
  {
    "name": "pepperoni pizza slice",
    "sugar": 10,
    "calories": 39,
    "totalFat": 11,
    "sodium": 46,
    "protein": 15,
    "carbs": 47,
    "userId": 3,
    "servingUnit": "much",
    "quantity": 2,
    "date": "5/17/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 15,
    "calories": 60,
    "totalFat": 3,
    "sodium": 21,
    "protein": 11,
    "carbs": 27,
    "userId": 1,
    "servingUnit": "gallon",
    "quantity": 4,
    "date": "5/9/2018"
  },
  {
    "name": "spaghetti",
    "sugar": 30,
    "calories": 61,
    "totalFat": 19,
    "sodium": 70,
    "protein": 6,
    "carbs": 11,
    "userId": 7,
    "servingUnit": "bucket",
    "quantity": 3,
    "date": "5/17/2018"
  },
  {
    "name": "turkey",
    "sugar": 8,
    "calories": 216,
    "totalFat": 20,
    "sodium": 138,
    "protein": 14,
    "carbs": 13,
    "userId": 9,
    "servingUnit": "handful",
    "quantity": 2,
    "date": "5/3/2018"
  },
  {
    "name": "wine",
    "sugar": 31,
    "calories": 253,
    "totalFat": 11,
    "sodium": 136,
    "protein": 1,
    "carbs": 27,
    "userId": 5,
    "servingUnit": "medium",
    "quantity": 1,
    "date": "5/19/2018"
  },
  {
    "name": "lasagna",
    "sugar": 15,
    "calories": 244,
    "totalFat": 5,
    "sodium": 71,
    "protein": 2,
    "carbs": 26,
    "userId": 4,
    "servingUnit": "handful",
    "quantity": 1,
    "date": "5/13/2018"
  },
  {
    "name": "bacon",
    "sugar": 9,
    "calories": 87,
    "totalFat": 1,
    "sodium": 108,
    "protein": 4,
    "carbs": 33,
    "userId": 10,
    "servingUnit": "L",
    "quantity": 2,
    "date": "4/27/2018"
  },
  {
    "name": "popcorn",
    "sugar": 6,
    "calories": 243,
    "totalFat": 3,
    "sodium": 146,
    "protein": 15,
    "carbs": 20,
    "userId": 7,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/6/2018"
  },
  {
    "name": "cola",
    "sugar": 1,
    "calories": 94,
    "totalFat": 6,
    "sodium": 7,
    "protein": 13,
    "carbs": 10,
    "userId": 8,
    "servingUnit": "lbs",
    "quantity": 4,
    "date": "5/10/2018"
  },
  {
    "name": "grapes",
    "sugar": 16,
    "calories": 139,
    "totalFat": 5,
    "sodium": 69,
    "protein": 7,
    "carbs": 28,
    "userId": 8,
    "servingUnit": "bucket",
    "quantity": 4,
    "date": "5/14/2018"
  },
  {
    "name": "milk",
    "sugar": 13,
    "calories": 62,
    "totalFat": 25,
    "sodium": 75,
    "protein": 15,
    "carbs": 20,
    "userId": 3,
    "servingUnit": "small",
    "quantity": 3,
    "date": "5/4/2018"
  },
  {
    "name": "bacon",
    "sugar": 31,
    "calories": 271,
    "totalFat": 9,
    "sodium": 2,
    "protein": 3,
    "carbs": 45,
    "userId": 5,
    "servingUnit": "",
    "quantity": 3,
    "date": "5/8/2018"
  },
  {
    "name": "cola",
    "sugar": 26,
    "calories": 138,
    "totalFat": 22,
    "sodium": 72,
    "protein": 12,
    "carbs": 49,
    "userId": 6,
    "servingUnit": "",
    "quantity": 5,
    "date": "5/13/2018"
  },
  {
    "name": "fried chicken",
    "sugar": 29,
    "calories": 171,
    "totalFat": 7,
    "sodium": 139,
    "protein": 4,
    "carbs": 21,
    "userId": 5,
    "servingUnit": "oz",
    "quantity": 3,
    "date": "5/16/2018"
  },
  {
    "name": "whiskey",
    "sugar": 8,
    "calories": 139,
    "totalFat": 2,
    "sodium": 39,
    "protein": 6,
    "carbs": 4,
    "userId": 8,
    "servingUnit": "small",
    "quantity": 4,
    "date": "5/13/2018"
  },
  {
    "name": "circus peanuts",
    "sugar": 4,
    "calories": 15,
    "totalFat": 12,
    "sodium": 14,
    "protein": 1,
    "carbs": 12,
    "userId": 1,
    "servingUnit": "L",
    "quantity": 3,
    "date": "4/20/2018"
  },
  {
    "name": "ribs",
    "sugar": 34,
    "calories": 224,
    "totalFat": 16,
    "sodium": 23,
    "protein": 8,
    "carbs": 20,
    "userId": 7,
    "servingUnit": "",
    "quantity": 4,
    "date": "5/6/2018"
  },
  {
    "name": "sausage",
    "sugar": 7,
    "calories": 171,
    "totalFat": 10,
    "sodium": 39,
    "protein": 7,
    "carbs": 35,
    "userId": 3,
    "servingUnit": "much",
    "quantity": 4,
    "date": "4/30/2018"
  },
  {
    "name": "whiskey",
    "sugar": 9,
    "calories": 264,
    "totalFat": 14,
    "sodium": 118,
    "protein": 11,
    "carbs": 8,
    "userId": 6,
    "servingUnit": "lbs",
    "quantity": 3,
    "date": "5/1/2018"
  }
]
module.exports = FoodLogSeed
